[package]
name = "fireshot_core"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = { version = "2", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
